# Generated by Django 3.0.8 on 2020-08-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_directions',
            field=models.ManyToManyField(to='tasks.WorkDirection'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_types',
            field=models.ManyToManyField(to='tasks.WorkType'),
        ),
    ]
