version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    # Подождём установки postgres перед тем как запустим миграции
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 3; done;
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
