version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
  web:
    build: .
    # Подождём установки postgres перед тем как запустим миграции
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 3; done;
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn crm.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload"
    volumes:
      - .:/code
      - ./media-data:/code/media/
    expose:
      - 8000
    depends_on:
      - db
