# Generated by Django 3.0.8 on 2020-07-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('comment', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Требования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('questioned', 'Есть вопросы'), ('rated', 'Оцененная'), ('rejected', 'Отклоненная'), ('in-progress', 'В работе')], default='new', max_length=11, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('wanted_deadline', models.DateField(null=True, verbose_name='Желаемый срок')),
                ('deadline', models.DateField(null=True)),
                ('phone', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('whats_app', models.CharField(max_length=150, verbose_name="What's App")),
                ('work_type', models.CharField(choices=[('test_1', 'Тест1'), ('test_2', 'Тест2')], max_length=10, verbose_name='Тип работы')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('change_status', 'Поменять статус '),),
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='tasks.File')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.Task')),
            ],
        ),
    ]
