# Generated by Django 3.0.8 on 2020-08-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('comment', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('name', models.CharField(max_length=150, verbose_name='Основная идея')),
                ('text', models.TextField(verbose_name='Исходные данные и требования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('questioned', 'Есть вопросы'), ('rated', 'Оцененная'), ('rejected', 'Отклоненная'), ('in-progress', 'В работе'), ('completed', 'Завершена')], default='new', max_length=11, verbose_name='Статус')),
                ('wanted_deadline', models.DateField(null=True, verbose_name='Желаемый срок')),
                ('teacher_name', models.CharField(max_length=100, null=True, verbose_name='ФИО руководителя')),
                ('phone', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('whats_app', models.CharField(max_length=150, verbose_name="What's App")),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('prepayment_received', models.BooleanField(default=False, verbose_name='Предоплата внесена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('can_rate_task', 'Может оценить заявку'), ('can_put_to_work', 'Может отдать в работу'), ('can_see_extra', 'Может смотреть дополнительную информацию')),
            },
        ),
        migrations.CreateModel(
            name='WorkDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='tasks.File')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='work_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.WorkDirection'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.WorkType'),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено'), ('in-work', 'Принят к работе')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='tasks.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-price'],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
