# Generated by Django 3.0.8 on 2020-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
