# Generated by Django 3.0.8 on 2020-08-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskstatus_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.WorkDirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.WorkType', verbose_name='Тип работы'),
        ),
    ]
