# Generated by Django 3.0.8 on 2020-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200706_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('rated', 'Оцененная'), ('rejected', 'Отклоненная'), ('in-progress', 'В работе')], default='new', max_length=11, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Требования'),
        ),
    ]
