# Generated by Django 3.0.8 on 2020-07-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200726_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': (('can_change_status', 'Может поменять статус'),)},
        ),
    ]
