# Generated by Django 3.1 on 2020-09-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200906_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='groups',
            new_name='group',
        ),
    ]
