# Generated by Django 3.0.8 on 2020-07-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200719_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.File'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.File'),
        ),
    ]
