# Generated by Django 3.1 on 2020-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200906_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='promocode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
