# Generated by Django 3.0.8 on 2020-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200726_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='decision',
            field=models.CharField(choices=[('rejected', 'Отклоненная'), ('taken', 'Взята в рабту'), ('completed', 'Завершена')], default='taken', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('questioned', 'Есть вопросы'), ('rated', 'Оцененная'), ('rejected', 'Отклоненная'), ('in-progress', 'В работе'), ('completed', 'Завершена')], default='new', max_length=11, verbose_name='Статус'),
        ),
    ]
