# Generated by Django 3.0.8 on 2020-07-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200726_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': (('can_rate_task', 'Может оценить заявку'), ('can_put_to_work', 'Может отдать в работу'))},
        ),
    ]
