# Generated by Django 3.1 on 2020-09-13 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200913_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='promocode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Промокод'),
        ),
    ]
