# Generated by Django 3.1 on 2020-09-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200913_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together=set(),
        ),
    ]
