# Generated by Django 3.1 on 2020-09-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200913_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={},
        ),
    ]
