# Generated by Django 3.0.8 on 2020-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200803_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='type',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено')], default='accepted', max_length=8),
            preserve_default=False,
        ),
    ]
