# Generated by Django 3.1 on 2020-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200913_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
