# Generated by Django 3.0.8 on 2020-08-04 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_taskstatus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='type',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено'), ('in-work', 'Принят к работе')], max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('task', 'user')},
        ),
    ]
