# Generated by Django 3.1 on 2020-12-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20201223_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='type',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено'), ('in-work', 'Принят к работе')], default='new', max_length=8),
        ),
    ]
