# Generated by Django 3.0.8 on 2020-08-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20200804_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': (('can_rate_task', 'Может оценить заявку'), ('can_put_to_work', 'Может отдать в работу'), ('can_see_extra', 'Может смотреть дополнительную информацию'))},
        ),
    ]
