# Generated by Django 3.1 on 2020-12-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20201225_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='type',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('in-work', 'Принят к работе')], default='new', max_length=8),
        ),
    ]
