# Generated by Django 3.0.8 on 2020-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20200808_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer_name',
            field=models.CharField(default='isdmfp;msdfg', max_length=150, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(default='asdfaosdijf', verbose_name='Заметки'),
            preserve_default=False,
        ),
    ]
