# Generated by Django 3.0.8 on 2020-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20200808_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['-price']},
        ),
        migrations.AddField(
            model_name='task',
            name='prepayment_received',
            field=models.BooleanField(default=False, verbose_name='Предоплата внесена'),
        ),
    ]
